fastlane_version "2.69.3"

default_platform :ios

platform :ios do
  desc "Install dependencies"
  lane :bootstrap do
    bundle install
    keys
    cocoapods
  end

  desc "Run tests"
  lane :test do
    cocoapods
    run_tests(
      workspace: "Banjo.xcworkspace",
      scheme: "Banjo",
      clean: false
    )
  end

  desc "Generate new certificates"
  lane :certs do
    # set readonly to false, if you need to generate new certs
    match(type: "development", readonly: false)
    match(type: "adhoc", readonly: false)
    match(type: "appstore", readonly: false)
  end

  desc "Deploy test build using Crashlytics Beta"
  lane :beta do
    match(type: 'adhoc', readonly: true)

    gym(
      workspace: "Banjo.xcworkspace",
      scheme: "Banjo",
      export_method: "ad-hoc",
      export_options: {
        provisioningProfiles: {
          "com.ParkesTwins.Banjo" => "match AdHoc com.ParkesTwins.Banjo"
        }
      }
    )

    crashlytics(
      api_token: "b987616e1a3e27c4bda7906d4c30b13800145ce8",
      build_secret: "dd6830628db07bc1ae61e1294b337f9b9926d2afe4b1d5c60d72496f8a88629d"
    )

    upload_symbols_to_crashlytics
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    match(type: "appstore")
    gym(scheme: "Banjo")
    deliver(force: true)
  end
end
