fastlane_version "2.77.1"

default_platform :ios

platform :ios do
  before_all do
    ENV["SLACK_URL"] = "https://hooks.slack.com/services/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"
  end

  desc "Install dependencies"
  lane :bootstrap do
    bundle install
    keys
    cocoapods
  end

  desc "Test lane for Spur demonstration"
  lane :spur do
    snapshot
  end

  desc "Run tests"
  lane :test do
    cocoapods
    run_tests(
      workspace: "Banjo.xcworkspace",
      scheme: "Banjo",
      clean: false
    )
  end

  desc "Generate new certificates"
  lane :certs do
    # set readonly to false, if you need to generate new certs
    match(type: "development", readonly: false, force: true)
    match(type: "adhoc", readonly: false, force: true)
    match(type: "appstore", readonly: false, force: true)
  end

  desc "Deploy test build using Crashlytics Beta"
  lane :beta do
    match(type: 'adhoc', readonly: true)

    gym(
      workspace: "Banjo.xcworkspace",
      scheme: "Banjo",
      export_method: "ad-hoc",
      export_options: {
        provisioningProfiles: {
          "com.ParkesTwins.Banjo" => "match AdHoc com.ParkesTwins.Banjo"
        }
      }
    )

    crashlytics(
      api_token: "b987616e1a3e27c4bda7906d4c30b13800145ce8",
      build_secret: "dd6830628db07bc1ae61e1294b337f9b9926d2afe4b1d5c60d72496f8a88629d",
      groups: ['parkestwins'],
      notes: "Added screenshots to game detail view.",
      notifications: true
    )

    upload_symbols_to_crashlytics

    slack(message: "Uploaded new #{bundleID} build to Crashlytics Beta.")
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    match(type: "appstore")
    gym(scheme: "Banjo")
    deliver(force: true)
  end
end
